[package]
name = "nfe_cotrisoja_utils"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.37", features = ["full"] }
notify = { version = "6.1" }
clap = { version = "4.5", features = ["derive"] }

